name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"  # Runs at 18:00 UTC daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    strategy:
      matrix:
        node-version: [20.x]   # Specify the version you want to use
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main  # Specify the branch you want to check out if different

      - name: Generate GitHub profile 3D contributions
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name Divyanshu-RS
          git config user.email divyanshuranjan.9999@gmail.com
          git add -A .
          git commit -m "generated"
          git push
