name: GitHub-Profile-3D

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d
    steps:
      - uses: actions/checkout@v3
      - uses: Divyanshu-RS/github-profile-3d@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name Divyanshu-RS
          git config user.email divyanshuranjan.9999@gmail.com
          git add -A .
          git commit -m "generated"
          git push
