name: Metrics
 run:
# Insert the generated SVG into the README
    sed -i '/<!-- START_SECTION:calendar -->/,/<!-- END_SECTION:calendar -->/c\
    <!-- START_SECTION:calendar -->\n\
    ![Isometric Calendar](./metrics.plugin.isocalendar.svg)\n\
    <!-- END_SECTION:calendar -->' README.md
 
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
